// apps/app/src/routes/Home.tsx
import React from "react";
import { Timeline, Text } from "@mantine/core";

import { PageLayout } from "../components/PageLayout";

export function Home() {
  return (
    <PageLayout className="pt-16">
      <Timeline active={2} bulletSize={24} lineWidth={2}>
        <Timeline.Item
          bullet={1}
          title="First, enter your hosting configuration"
        >
          <Text color="dimmed" size="sm">
            (S3, Azure, GCP, etc.)
          </Text>
        </Timeline.Item>

        <Timeline.Item
          bullet={2}
          title="Next, start creating your environments."
        >
          <Text color="dimmed" size="sm">
            (dev, staging, prod, etc.)
          </Text>
        </Timeline.Item>

        <Timeline.Item bullet={3} title="Then, create your feature flags.">
          <Text color="dimmed" size="sm">
            (Toggle, Gradual, Selective, etc.)
          </Text>
        </Timeline.Item>
      </Timeline>
    </PageLayout>
  );
}

// apps/web/src/views/Home.vue
<template>
  <div class="home">
    <p class="getting-started-intro prose">
      Getting started is easy.
    </p>
    <Icon :icon="icons.flag" class="logo" />
    <ol class="getting-started-list">
      <li>First, enter your hosting configuration. (S3, Azure, GCP, etc.)</li>
      <li>
        Next, start creating your environments. (dev, staging, prod, etc.)
      </li>
      <li>Then, create your feature flags.</li>
    </ol>
  </div>
</template>

<style lang="postcss" scoped>
.home {
  @apply flex flex-col justify-center items-center h-3/4 w-full lg:w-3/4 m-auto rounded-lg bg-secondary-color;
}

.title {
  @apply text-7xl;
}

.logo {
  font-size: 420px;
  @apply text-indigo-500
}

.getting-started-intro {
  @apply text-3xl;
}

.getting-started-list {
  list-style: none;
  & li {
    @apply text-xl mb-4;
  }
}
</style>

<script lang="ts">
import { Icon, InlineIcon } from "@iconify/vue";
import flagIcon from "@iconify-icons/dashicons/flag";
import { defineComponent } from "vue";
import store from "@/store";

export default defineComponent({
  name: "Home",
  store,
  data: function() {
    return {
      icons: {
        flag: flagIcon
      }
    };
  },
  components: {
    Icon
  }
});
</script>
